POST http://localhost:8080/register
content-type: application/json

{
  "email": "yaba.ernesto@gmail.com",
  "password": "123456"
}

###

POST http://localhost:8080/login
content-type: application/json

{
  "email": "yaba.ernesto@gmail.com",
  "password": "123456"
}

###

GET http://localhost:8080/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTk2ZGUyOWI0NWY2ODY2NmY5YzljODIiLCJpYXQiOjE3ODgzNTA0NzAsImV4cCI6MTc4ODM1MTM3MH0.KQ8cfI-XwouhVLw8YMxpEwDSYVHhmO8rKyQ1_UeAnD4

###

POST http://localhost:8080/refresh-token
content-type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTk2ZGUyOWI0NWY2ODY2NmY5YzljODIiLCJpYXQiOjE3ODgzNTA1MTAsImV4cCI6MTc5MDk0MjUxMH0.uYGpHh1bKK_csWLyXliAKjj2fuO3eX20sOI4vlj_oVc"
}
