POST http://localhost:8080/register
content-type: application/json

{
  "email": "yabaernesto@gmail.com",
  "password": "123456",
  "firstName": "Yaba",
  "lastName": "Ernesto",
  "age": 25
}

###

POST http://localhost:8080/login
content-type: application/json

{
  "email": "yaba.ernesto@gmail.com",
  "password": "123456"
}

###

GET http://localhost:8080/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YWFiZmM3ZmRhNDk2YWQ1YWVlZjZmOWMiLCJpYXQiOjE3ODk2NTYxOTIsImV4cCI6MTc4OTY1NzA5Mn0.muxR5YhrBc3p22xJ8hwqUtwQER-FTNasB8KP3iENrig

###

POST http://localhost:8080/refresh-token
content-type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTk2ZGUyOWI0NWY2ODY2NmY5YzljODIiLCJpYXQiOjE3ODgzNTA1MTAsImV4cCI6MTc5MDk0MjUxMH0.uYGpHh1bKK_csWLyXliAKjj2fuO3eX20sOI4vlj_oVc"
}
